### ISSUE TITLE
Docker Hub automated builds

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p-relay-server#3]
There is still an issue with the docker hub automated builds. I triggered a new release to see if the build worked after the docker hub integration. However, I got an error:

```
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
please ensure the correct public key is added to the list of trusted keys for this repository (128)
```

It seems that the docker integration in github needs to be configured, but I cannot access the repo settings. @jacobheun can you have a look?

**Comment by lidel** [comment]
Marking this as bug + adding to maintenance board because we  have 
- https://github.com/libp2p/js-libp2p-relay-server#docker
- https://hub.docker.com/r/libp2p/js-libp2p-relay-server (but it is empty)

**Comment by TinyTb** [comment]
Closing this issue because we have higher priorities, like relay v2. Also, this has been open > 2 years, and we're not confident in the impact if this gets done. If anyone feels otherwise, please feel free to re-open or create a new issue :)
